name: DB Migrate (Drizzle Push)

on:
  workflow_dispatch:
    inputs:
      database_url:
        description: 'DATABASE_URL (leave empty to use secret)'
        required: false
        default: ''

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        run: corepack enable

      - name: Install
        run: pnpm i --frozen-lockfile

      - name: Generate migrations
        env:
          DATABASE_URL: ${{ github.event.inputs.database_url || secrets.DATABASE_URL }}
        run: pnpm drizzle:generate

      - name: Push migrations
        env:
          DATABASE_URL: ${{ github.event.inputs.database_url || secrets.DATABASE_URL }}
        run: pnpm drizzle:push

