name: Build static site to 'site' branch (for Vercel)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'schemas/**'
      - 'scripts/**'
      - 'data/**'
      - 'web/**'
      - 'Makefile'
      - '.github/workflows/build-site-branch.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build static site (HTML only)
        run: |
          make publish

      - name: Publish to 'site' branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out/site
          publish_branch: site
          keep_files: false
          force_orphan: true

